name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      #Code Checkout
      - name: Checkout
        uses: actions/checkout@v4
      # Install .Net SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
     
     # Install NPM dependencies
      - name: Install NPM dependencies
        working-directory: ./ResumeApp
        run: npm i
        
      # Compile Tailwindcss
      - name: Compile Tailwindcss
        working-directory: ./ResumeApp/
        run: npx tailwindcss -i ./Styles/tailwindcss - o ./wwwroot/css/tailwindcss

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish/wwwroot
          force_orphan: true
          publish_branch: gh-pages
