name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      #Code Checkout
      - name: Checkout
        uses: actions/checkout@v4
      # Install .Net SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
     
     # Install NPM dependencies
      - name: Install NPM dependencies
        working-directory: ./ResumeApp
        run: npm i
        
      # Compile Tailwindcss
      - name: Compile Tailwindcss
        working-directory: ./ResumeApp/
        run: npx @tailwindcss/cli -i ./Styles/input.css -o ./wwwroot/tailwind.css

      - name: Publish Blazor app
        run: dotnet publish ResumeApp.csproj -c Release -o release --nologo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Action specifically designed for deploying to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub Token automatically provided
          publish_dir: ./release/wwwroot # The directory containing your published Blazor app's static files
          publish_branch: gh-pages # The branch where GitHub Pages will serve from (will be created if it doesn't exist)
          force_orphan: true # Forces the gh-pages branch to be re-created from scratch on each deploy

